[package]
name = "rust_ls"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ls"
path = "src/rust_ls.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
